#!/usr/bin/env bash
# To enable this hook, copy it to .git/hooks
# Make sure it's executable

# Before we commit, edit the hash of the last commit into the langpack
# subheading, which makes it easy to see that our changes applied.
HASH=$(git rev-parse --short HEAD | tr -d '\n')
sed -i '' "s/\(com.equella.core.langpack.subheading=.*\) (.*)/\1 (${HASH})/g" pack/resource-centre.properties
git add pack/resource-centre.properties
